"""Verified explanation of the project scanning pipeline.

Review this source-inspected contract whenever the scanner or analyzer changes.
"""


def format_verified_project_pipeline():
    """Describe the source-inspected scanner/analyzer contract."""
    return "\n".join([
        "Verified scanner and analyzer explanation",
        "",
        "1. Project scanning",
        "",
        "project_scanner.py defines scan_project(project_path).",
        "It checks whether the supplied path exists and",
        "is a directory.",
        "",
        "It recursively examines directory entries,",
        "skips symbolic-link entries, non-files and",
        "paths containing ignored directory names.",
        "",
        "It uses detect_language() to identify supported",
        "files and skips files with unknown languages.",
        "",
        "On success, it returns a list of dictionaries",
        "containing each file's path and language,",
        "together with a project-level error of None.",
        "",
        "A missing or non-directory project path",
        "produces a project-level error instead.",
        "The scanner does not catch every possible filesystem exception.",
        "",
        "2. Project analysis",
        "",
        "project_analyzer.py defines analyze_project().",
        "It first calls scan_project() and propagates",
        "any returned project-level error as (None, error).",
        "",
        "For each discovered file, it calls read_code_file().",
        "If read_code_file() returns an error, the analyzer",
        "records the file's path, language and error, then",
        "continues to the next file. That error record has",
        "no analysis or content key.",
        "",
        "After a successful read, it calls analyze_code()",
        "with the source content and detected language.",
        "On successful analysis, it stores path, language,",
        "content and analysis in the file's result dictionary.",
        "",
        "3. Error-handling contract",
        "",
        "After completing the loop, analyze_project() returns",
        "(project_files, None). The project-level error can",
        "therefore be None even when individual file-reading",
        "failures are recorded in project_files.",
        "",
        "analyze_project() does not catch exceptions raised by analyze_code().",
        "If analyze_code() raises an exception, it propagates",
        "and processing stops; it is not converted into a per-file error dictionary.",
        "No normal (project_files, None) result is returned in that case.",
        "",
        "Callers must check for a per-file error before accessing its analysis.",
    ])
